core/urls.py
from django.urls import path
from .views import ItemDetailView, CheckoutView, HomeView, add_to_cart, remove_from_cart, OrderSummaryView,\
    remove_single_item_from_cart, PaymentView, AboutView, ContactView

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
]

nedverlu_market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path("paystack", include(('paystack.urls', 'paystack'), namespace='paystack')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paystack/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import settings
from . import views
# urlpatterns = [
  #  url(r'^verify-payment/(?P<order>[\w.@+-]+)/$',
   #     views.verify_payment, name='verify_payment'),
   # url(r'^failed-verification/(?P<order_id>[\w.@+-]+)/$',
    #    views.failure_redirect_view, name='failed_verification'),
   # url(r'^successful-verification/(?P<order_id>[\w.@+-]+)/$',
    #    views.success_redirect_view,
     #   name='successful_verification'),
   # url(r'^failed-page/$',
    #    views.TemplateView.as_view(template_name='paystack/failed-page.html'), name='failed_page'),
   # url(r'^success-page/$',
    #    views.TemplateView.as_view(template_name='paystack/success-page.html'), name='success_page'),
    #url(r'^webhook/$', csrf_exempt(views.webhook_view), name='webhook'),
#]

urlpatterns = [
    path('verify-payment/<order>/', views.verify_payment, name='verify_payment'),
    path('failed-verification/<order_id>/', views.failure_redirect_view, name='failed_verification'),
    path('successful-verification/<order_id>/', views.success_redirect_view, name='successful_verification'),
    path('failed-page/', views.TemplateView.as_view(template_name='paystack/failed-page.html'), name='failed_page'),
    path('success-page/', views.TemplateView.as_view(template_name='paystack/success-page.html'), name='success_page'),
    path('webhook/', csrf_exempt(views.webhook_view), name='webhook'),
]

core/models.py
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField

CATEGORY_CHOICES = (
    ('J', 'Jamb'),
    ('W', 'Waec'),
    ('G', 'GCE'),
    ('N', 'Neco'),
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'Danger')
)

class Item(models.Model):
    title = models.CharField(max_length=100)
    #price = models.DecimalField(decimal_places=2, max_digits=20, default=0.00)
    price = models.IntegerField()
    discount_price = models.IntegerField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    availability = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)


    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()



class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipment_details = models.ForeignKey(
        'ShipmentDetails', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total


class ShipmentDetails(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    email = models.EmailField()
    phone_no = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Shipment details'


class Payment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username



class AddSlider(models.Model):
    image = models.ImageField(upload_to='slider', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

templates/main/about.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

  <!--================About Banner Area =================-->
    
    <section class="banner_area">
      <div class="banner_inner d-flex align-items-center">
        <div class="container">
          <div
            class="banner_content d-md-flex justify-content-between align-items-center"
          >
            <div class="mb-3 mb-md-0">
              <h2>About Us</h2>
              <p>Very us move be blessed multiply night</p>
            </div>
            <div class="page_link">
              <a href="index.html">Home</a>
              <a href="about.html">About Us</a>
            </div>
          </div>
        </div>
      </div>
    </section>

  <!--================End About Banner Area =================-->
    
    <section class="section_gap">
      <div class="container">
          <div class="row">
              <div class="col-md-8 col-sm-8 col-xs-8">
                  <h4>
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut nunc id leo porttitor tristique. Vivamus erat lorem, dictum sit amet sem id,
                      ultrices ultricies nisi. Ut nisi libero, faucibus et felis non, tempor accumsan nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus.

                  </h4>
                  <h4>
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut nunc id leo porttitor tristique. Vivamus erat lorem, dictum sit amet sem id,
                      ultrices ultricies nisi. Ut nisi libero, faucibus et felis non, tempor accumsan nunc. In ut malesuada nisl, eu ultricies nisl.

                  </h4>
                  <h4>
                      Vivamus semper eros eget sapien bibendum consequat. Vivamus quis dapibus sem, vitae ultricies tortor. Ut id blandit tortor, id consequat ex. Nullam nec interdum elit, eu rutrum ante. Donec eget lorem massa.
                      Maecenas sit amet placerat dolor.
                  </h4>
                  <h4>
                      Vivamus semper eros eget sapien bibendum consequat. Vivamus quis dapibus sem, vitae ultricies tortor. Ut id blandit tortor, id consequat ex. Nullam nec interdum elit, eu rutrum ante. Donec eget lorem massa.
                      Maecenas sit amet placerat dolor.
                  </h4>
                  <h4>
                      Vivamus semper eros eget sapien bibendum consequat. Vivamus quis dapibus sem, vitae ultricies tortor. Ut id blandit tortor, id consequat ex. Nullam nec interdum elit, eu rutrum ante. Donec eget lorem massa.
                      Maecenas sit amet placerat dolor.
                  </h4>
                  <h4>
                      Vivamus semper eros eget sapien bibendum consequat. Vivamus quis dapibus sem, vitae ultricies tortor. Ut id blandit tortor, id consequat ex. Nullam nec interdum elit, eu rutrum ante. Donec eget lorem massa.
                      Maecenas sit amet placerat dolor.
                  </h4>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-4">
              </div>
          </div>
          
        </div>
    </section>

{% endblock %}

templates/main/checkout.html
{% extends 'main/base.html' %}
{% load static %}
{% load humanize %} <!-- "load humanize" makes numbers to have commas -->
{% load crispy_forms_tags %}
{% block head %}
    <title>Checkout</title>
{% endblock head %}
{% block content %}

    <!--================Home Banner Area =================-->
    <section class="banner_area">
      <div class="banner_inner d-flex align-items-center">
        <div class="container">
          <div
            class="banner_content d-md-flex justify-content-between align-items-center"
          >
            <div class="mb-3 mb-md-0">
              <h2>Product Checkout</h2>
              <p>Very us move be blessed multiply night</p>
            </div>
            <div class="page_link">
              <a href="index.html">Home</a>
              <a href="checkout.html">Product Checkout</a>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--================End Home Banner Area =================-->

    <!--================Checkout Area =================-->
    <section class="checkout_area section_gap">
      <div class="container">
        <div class="billing_details">
          <div class="row">
            <div class="col-lg-9 col-md-9 col-sm-9">
              <div class="order_box">
                <h2>Your Shipment Details</h2>
                
                   <form method="POST">
                       {% csrf_token %}
                            <div class="mt-10">
                                <label for="email" class="">Email</label>
                                                {{ form.email }}
                            </div>
                           
                           <div class="mt-10">
                               <label for="phone_no" class="">Phone Number</label>
                                {{ form.phone_no }}
                           </div>
                       <hr>
                        <button class="main_btn" type="submit" name="url 'core:payment'">Make Payment</button>
                    </form>
              </div>
            </div>
              <div class="col-lg-3 col-md-3 col-sm-3">
                  {% include "main/order_snippet.html" %}
                  <div class="row">
                      <div class="col-md-12 col-sm-12 col-xs-12">
                          <img src="{% static 'main/img/card-logos.jpg ' %}" alt="" style="width: 55%;">
                      </div>
                  </div>
              </div>

          </div>
        </div>
      </div>
    </section>
    <!--================End Checkout Area =================-->

{% endblock %}

templates/main/contact.html
{% extends 'main/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %} <!-- "load humanize" makes numbers to have commas -->
{% block content %}



    <!--================Home Banner Area =================-->
    <section class="banner_area">
      <div class="banner_inner d-flex align-items-center">
        <div class="container">
          <div
            class="banner_content d-md-flex justify-content-between align-items-center"
          >
            <div class="mb-3 mb-md-0">
              <h2>Contact Us</h2>
              <p>Very us move be blessed multiply night</p>
            </div>
            <div class="page_link">
              <a href="index.html">Home</a>
              <a href="contact.html">Contact Us</a>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--================End Home Banner Area =================-->

    <!-- ================ contact section start ================= -->
  <section class="section_gap">
    <div class="container">

      <div class="row">
        <div class="col-12">
          <h2 class="contact-title">Get in Touch</h2>
        </div>
        <div class="col-lg-8 mb-4 mb-lg-0">
          <form class="form-contact contact_form" action="" method="POST">
            {% csrf_token %}
            <div class="row">
              <div class="col-12">
                <div class="form-group">
                    {{ form.message }}
                </div>
              </div>

              <div class="col-sm-6">
                <div class="form-group">
                  {{ form.from_email }}
                </div>
              </div>
              <div class="col-12">
                <div class="form-group">
                  {{ form.subject }}
                </div>
              </div>
            </div>
            <div class="form-group mt-lg-3">
              <button type="submit" class="main_btn">Send Message</button>
            </div>
          </form>


        </div>

        <div class="col-lg-4">
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-home"></i></span>
            <div class="media-body">
              <h3>Buttonwood, California.</h3>
              <p>Rosemead, CA 91770</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-tablet"></i></span>
            <div class="media-body">
              <h3><a href="tel:454545654">00 (440) 9865 562</a></h3>
              <p>Mon to Fri 9am to 6pm</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-email"></i></span>
            <div class="media-body">
              <h3><a href="mailto:support@colorlib.com">support@colorlib.com</a></h3>
              <p>Send us your query anytime!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
	<!-- ================ contact section end ================= -->

{% endblock %}

templates/main/home.html
{% extends 'main/base.html' %}
{% load static %}
{% load humanize %} <!-- "load humanize" makes numbers to have commas -->
{% block content %}




    <!--================Home Banner Area =================-->


    <section class="banner_area">
      <div class="banner_inner d-flex align-items-center">
        <div class=""> <!--There was formerly a class of container-->
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="1"></li>
              <li data-target="#myCarousel" data-slide-to="2"></li>
              <li data-target="#myCarousel" data-slide-to="3"></li>
              <li data-target="#myCarousel" data-slide-to="4"></li>
              <li data-target="#myCarousel" data-slide-to="5"></li>
            </ol>

            <!-- Wrapper for slides -->

            <div class="carousel-inner">
            {% for slider in slider %}
              {% if forloop.counter == 1 %}
              <div class="item active">
                {% else %}
                <div class="item">
                {% endif %}
                <img src="{{ slider.image.url }}" alt="" style="width:100%;">
                <div class="carousel-caption">
                  <h3>Los Angeles</h3>
                  <p>LA is always so much fun!</p>
                </div>
              </div>
              {% endfor %}
              </div>
            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>

        </div>
      </div>
      </div>
    </section>




  <!--================End Home Banner Area =================-->

<!--================  Product Area =================-->
  <section class="inspired_product_area">
    <div class="container section_gap">
      <div class="row justify-content-center">
        <div class="col-lg-12">
          <div class="main_title">
            <h2><span> Products</span></h2>
          </div>
        </div>
      </div>

      <div class="row">
        {% for item in item %}
        <div class="col-lg-3 col-md-6">
          <div class="single-product">
            <div class="product-img">
                <a href="{{ item.get_absolute_url }}">
                    <img class="img-fluid w-100" src="{{ item.image.url }}" alt="" />
                </a>
              <div class="p_icon">
                <a href="{{ item.get_absolute_url }}">BUY NOW</a>
              </div>
            </div>
            <div class="product-btm">
                <p>{{ item.get_category_display }}</p>
              <a href="{{ item.get_absolute_url }}" class="d-block">
                <h4>{{ item.title }}</h4>
              </a>
              <div class="mt-3">
                <span class="mr-4" style="font-size: 18px;">&#x20A6; <!-- mr-4: It is for margin-right -->
                  {% if item.discount_price %}
                    {{ item.discount_price|intcomma }}
                    {% else %}
                    {{ item.price|intcomma }}
                    {% endif %}
                </span>
                  {% if item.availability %}
                  <span style="font-weight: lighter; font-size: 16px; color: green;">In stock</span>
                  {% else %}
                  <span style="font-weight: lighter; font-size: 16px; color: green;">Out of stock</span>
                  {% endif %}
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

      </div>
    </div>
  </section>
  <!--================ End Product Area =================-->


    <!-- Start feature Area -->
  <section class="feature-area section_gap_bottom_custom">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-6">
          <div class="single-feature">
            <a href="{% static 'main/#" class="title">
              <i class="flaticon-money"></i>
              <h3>Money back gurantee</h3>
            </a>
            <p>Shall open divide a one</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6">
          <div class="single-feature">
            <a href="{% static 'main/#" class="title">
              <i class="flaticon-truck"></i>
              <h3>Free Delivery</h3>
            </a>
            <p>Shall open divide a one</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6">
          <div class="single-feature">
            <a href="" class="title">
              <i class="flaticon-support"></i>
              <h3>Alway support</h3>
            </a>
            <p>Shall open divide a one</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6">
          <div class="single-feature">
            <a href="{% static 'main/#" class="title">
              <i class="flaticon-blockchain"></i>
              <h3>Secure payment</h3>
            </a>
            <p>Shall open divide a one</p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End feature Area -->
    {% endblock %}

templates/main/order_snippet.html
{% load humanize %} <!-- "load humanize" makes numbers to have commas -->

<div class="panel panel-success">
    <div class="panel-heading">YOUR ORDER ({{ order.items.count }} item)</div>
      {% for order_item in order.items.all %}
        <div class="panel-body">
            <div class="media">
                <div class="media-left">
                  <img src="{{ order_item.item.image.url }}" class="media-object" style="width:60px">
                </div>
                <div class="media-body">
                  <h4 class="media-heading">{{ order_item.item.title }}</h4>
                  {% comment %}<p>{{ order_item.item.description|truncatechars:50 }}</p>{% endcomment %}
                    <p>&#x20A6; {{ order_item.item.price|intcomma }} <br> Qty: {{ order_item.quantity }} </p>
                </div>
              </div>
        </div>
      {% endfor %}
      <hr>
      <div class="panel-body">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-6">
                <h4><strong>Total</strong></h4>
            </div>

            <div class="col-md-6 col-sm-6 col-xs-6">
                <h4>&#x20A6; {{ order.get_total|intcomma }} </h4>
            </div>
        </div>
      </div>
  </div>

templates/main/order_summary.html
{% extends 'main/base.html' %}
{% load static %}
{% load humanize %} <!-- "load humanize" makes numbers to have commas -->
{% block head %}
    <title>Order Summary</title>
  {% endblock head %}
{% block content %}

    <!--================Home Banner Area =================-->
    <section class="banner_area">
      <div class="banner_inner d-flex align-items-center">
        <div class="container">
          <div
            class="banner_content d-md-flex justify-content-between align-items-center"
          >
            <div class="mb-3 mb-md-0">
              <h2>Order Summary</h2>
            </div>
            <div class="page_link">
              <a href="index.html">Home</a>
              <a href="checkout.html">Order Summary</a>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--================End Home Banner Area =================-->

    <!--================Checkout Area =================-->
    <section class="checkout_area section_gap">
      <div class="container">
        <div class="billing_details">
          <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
              <div class="order_box">
                <div class="table-responsive text-nowrap">
                <h2>Order Summary</h2>
                  <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Item </th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Item Price</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for order_item in object.items.all %}
                      <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ order_item.item.title }}</td>
                        <td>{{ order_item.item.price|intcomma }}</td>
                          <td> <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i style="color: #707070	;" class="fa fa-minus mr-2"></i></a>
                            {{ order_item.quantity }}
                            <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i style="color: #707070" class="fa fa-plus ml-2"></i></a>
                        </td>
                          <td>
                              {% if order_item.item.discount_price %}
                                {{ order_item.get_total_discount_item_price|intcomma }}
                                <span class="label label-success ml-2">Saving &#x20A6; {{ order_item.get_amount_saved|intcomma }}</span>
                              {% else %}
                                &#x20A6; {{ order_item.get_total_item_price|intcomma }}
                              {% endif %}
                              <a style="color:red;" href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                                  <i class="fa fa-trash float-right"></i>
                              </a>
                          </td>
                      </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5">Your cart is empty</td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class="btn btn-primary float-right" href="/">Continue shopping</a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% if object.get_total %}
                    <tr >
                        <td colspan="4" style="font-weight: bolder;">Order Total</td>
                        <td style="font-weight: bolder;">&#x20A6; {{ object.get_total|intcomma }}</td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class="btn btn-success float-right ml-2" href="/checkout/">Proceed to payment</a>
                            <a class="btn btn-primary float-right" href="/">Continue shopping</a>
                        </td>
                    </tr>
                    {% endif %}
                    </tbody>
                  </table>
        </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--================End Checkout Area =================-->
{% endblock %}

templates/main/product_detail.html
{% extends 'main/base.html' %}
{% load static %}
{% load humanize %} <!-- "load humanize" makes numbers to have commas -->
{% block head %}
    <title>Products</title>
  {% endblock head %}
{% block content %}


    <!--================Home Banner Area =================-->
    <section class="banner_area">
      <div class="banner_inner d-flex align-items-center">
        <div class="container">
          <div
            class="banner_content d-md-flex justify-content-between align-items-center"
          >
            <div class="mb-3 mb-md-0">
              <h2>Product Details</h2>
              <p>Very us move be blessed multiply night</p>
            </div>
            <div class="page_link">
              <a href="index.html">Home</a>
              <a href="product_detail.html">Product Details</a>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--================End Home Banner Area =================-->

    <!--================Single Product Area =================-->
    <div class="product_image_area">
      <div class="container">
        <div class="row s_product_inner">
          <div class="col-lg-6">
            <div class="s_product_img">
                    <img
                      class="d-block w-100"
                      src="{{ item.image.url }}"
                      alt=""
                    />
            </div>
          </div>
          <div class="col-lg-5 offset-lg-1">
            <div class="s_product_text">
              <h3>{{ object.title }}</h3>
              <h2>
                  {% if object.discount_price %}
                  <span class="mr-1">
                    <del>&#x20A6; {{ object.price|intcomma }}</del>
                  </span>
                  <span>&#x20A6; {{ object.discount_price|intcomma }}</span>
                  {% else %}
                  <span>&#x20A6; {{ object.price|intcomma }}</span>
                  {% endif %}
              </h2>
              <ul class="list">
                <li>
                  <a class="active" style="pointer-events: none; cursor: default;">
                    <span>Category </span> : {{ object.get_category_display }}</a
                  >
                </li>
                  {% if object.availability %}
                  <li>
                  <a class="active" style="pointer-events: none; cursor: default;">
                    <span>Availability </span> : In stock</a>
                </li>
                  {% else %}
                  <li>
                  <a class="active" style="pointer-events: none; cursor: default;" href="#">
                    <span>Availability </span> : Out of stock</a>
                </li>
                  {% endif %}

              </ul>
              <div>
                  <pre> {{ object.description|linebreaks }} </pre>
              </div>
                {% if item.availability %}
              <div class="card_area">
                <a class="main_btn btn btn-success" href="{{ object.get_add_to_cart_url }}">Add to cart
                    <i class="fa fa-shopping-cart ml-1"></i>
                </a>
                <a class="main_btn btn btn-danger" href="{{ object.get_remove_from_cart_url }}">Remove from cart</a>
              </div>
                {% else %}
                <div class="card_area">
                <a style="pointer-events: none; cursor: default;" class="main_btn btn btn-success" href="{{ object.get_add_to_cart_url }}">Add to cart
                    <i class="fa fa-shopping-cart ml-1"></i>
                </a>
                <a  style="pointer-events: none; cursor: default;" class="main_btn btn btn-danger" href="{{ object.get_remove_from_cart_url }}">Remove from cart</a>
              </div>
                {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--================End Single Product Area =================-->
    <br>
{% endblock %}